### PR TITLE
Change arg type to unsigned int from signed int

### PR DESCRIPTION
**Pull request by gwawiork**
I've found more tests that requires this change as was introduced in #1031

### CODE REVIEW

**Comment by gwawiork** [comment]
Looks like env issue: Macos build started failing. Can somebody look at it ?

/Users/runner/work/OpenCL-CTS/OpenCL-CTS/OpenCL-ICD-Loader/loader/linux/icd_linux_envvars.c:42:50: error: implicit declaration of function 'getgid' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    return geteuid() != getuid() || getegid() != getgid() ? NULL : khrIcd_getenv(name);
                                                 ^
4 errors generated.
make[2]: *** [CMakeFiles/OpenCL.dir/loader/linux/icd_linux_envvars.c.o] Error 1
make[1]: *** [CMakeFiles/OpenCL.dir/all] Error 2
make: *** [all] Error 2

**Comment by jrprice** [comment]
I've opened an ICD loader PR to fix the macOS failures:
https://github.com/KhronosGroup/OpenCL-ICD-Loader/pull/131

**Comment by gwawiork** [comment]
Thank you

**Review by jlewis-austin — APPROVED** [review]
It's kind of hard to verify with the reformatting, but I checked that all the literal "1" args became "1u"

**Review by nikhiljnv — APPROVED** [review]
LGTM.
