### ISSUE TITLE
 undefined reference to `clSetProgramSpecializationConstant'

### ISSUE THREAD

**Issue by mark-clayton** [KhronosGroup/OpenCL-CTS#165]

**Comment by mark-clayton** [comment]
Linker unable to find missing routine 
[ 86%] Linking CXX executable test_cpp_api
CMakeFiles/test_cpp_api.dir/main.cpp.o: In function `test_spec_consts_many_constants::run_test(_cl_device_id*, _cl_context*, _cl_command_queue*, int)':
/home/tnl/opencl/kronos/OpenCL-CTS/test_conformance/clcpp/api/test_spec_consts.hpp:235: undefined reference to `clSetProgramSpecializationConstant'
/home/tnl/opencl/kronos/OpenCL-CTS/test_conformance/clcpp/api/test_spec_consts.hpp:239: undefined reference to `clSetProgramSpecializationConstant'
CMakeFiles/test_cpp_api.dir/main.cpp.o: In function `test_spec_consts_different_types::run_test(_cl_device_id*, _cl_context*, _cl_command_queue*, int)':
/home/tnl/opencl/kronos/OpenCL-CTS/test_conformance/clcpp/api/test_spec_consts.hpp:396: undefined reference to `clSetProgramSpecializationConstant'
/home/tnl/opencl/kronos/OpenCL-CTS/test_conformance/clcpp/api/test_spec_consts.hpp:399: undefined reference to `clSetProgramSpecializationConstant'
/home/tnl/opencl/kronos/OpenCL-CTS/test_conformance/clcpp/api/test_spec_consts.hpp:402: undefined reference to `clSetProgramSpecializationConstant'
CMakeFiles/test_cpp_api.dir/main.cpp.o:/home/tnl/opencl/kronos/OpenCL-CTS/test_conformance/clcpp/api/test_spec_consts.hpp:405: more undefined references to `clSetProgramSpecializationConstant' follow
collect2: error: ld returned 1 exit status
test_conformance/clcpp/api/CMakeFiles/test_cpp_api.dir/build.make:224: recipe for target 'test_conformance/clcpp/api/test_cpp_api' failed
make[2]: *** [test_conformance/clcpp/api/test_cpp_api] Error 1
CMakeFiles/Makefile2:3062: recipe for target 'test_conformance/clcpp/api/CMakeFiles/test_cpp_api.dir/all' failed
make[1]: *** [test_conformance/clcpp/api/CMakeFiles/test_cpp_api.dir/all] Error 2
Makefile:83: recipe for t

**Comment by alycm** [comment]
Hi Mark,

`clSetProgramSpecializationConstant` was added in OpenCL 2.2, are you working with an implementation of a previous version of OpenCL?  There are different branches in the repository for different versions of OpenCL.

For example, if you are working with an OpenCL 2.1 implementation then you can use the `cl21_trunk` branch.

**Comment by kpet** [comment]
This is not an issue in the conformance tests, closing.
