### PR TITLE
Add missing include for gRandomSeed

### PR DESCRIPTION
**Pull request by jrprice**
Fixes a build issue on one of our platforms introduced by #1276.

### CODE REVIEW

**Comment by bashbaug** [comment]
Merging since this is straightforward also.

I still would be interested to know if there is a way to catch this error earlier.  Thanks!

**Comment by jrprice** [comment]
Missed your comment, sorry, but thanks for merging!

The way to catch this sort of thing earlier would be to try to compile all of our headers standalone as a separate step/job in CI. For example, you can reproduce the particular error that this PR fixes by invoking Clang on the header directly:

```
$ clang++ -w -std=c++11 test_common/harness/integer_ops_test_info.h
test_common/harness/integer_ops_test_info.h:87:20: error: unknown type name
      'gRandomSeed'
    MTdataHolder d(gRandomSeed);
                   ^
1 error generated.
```

I'm not sure if it'd always be this straightforward. There may be other flags that need to be passed to the compiler, e.g. macro definitions or include paths.
